#pragma once
#ifndef LAZYBOX_INCLUDE_LAZYBOX_BASE_COMPILEINFO_H_
#define LAZYBOX_INCLUDE_LAZYBOX_BASE_COMPILEINFO_H_

#include <cassert>

#ifdef NDEBUG
#define LBOX_NDEBUG 1
#else
#define LBOX_DEBUG 1
#endif

#endif // LAZYBOX_INCLUDE_LAZYBOX_BASE_COMPILEINFO_H_
