#pragma once
#ifndef LAZYBOX_INCLUDE_LAZYBOX_BASE_DEFINESTRTOOL_H_
#define LAZYBOX_INCLUDE_LAZYBOX_BASE_DEFINESTRTOOL_H_

#define SPLICE2_(A, B) A##B
#define SPLICE3_(A, B, C) A##B##C

#define SPLICE2(A, B) SPLICE2_(A, B)
#define SPLICE3(A, B, C) SPLICE3_(A, B, C)

#endif // LAZYBOX_INCLUDE_LAZYBOX_BASE_DEFINESTRTOOL_H_
